export default AppStyles = {
    primaryColor: '#FEC93B',
    secondaryColor: '#212134',
    primaryTextColor: '#32324D',
    secondaryTextColor: '#8E8EA9',
    primaryBackgroundColor: '#F5F5F5',
    secondaryBackgroundColor: '#FFF',
    primaryFontFamilyBold: 'DMSans_Bold',
    primaryFontFamilyMedium: 'DMSans_Medium',
    primaryFontFamilyRegular: 'DMSans_Regular',
    secondaryFontFamilyExtraBold: 'Mulish_ExtraBold',
    secondaryFontFamilyBold: 'Mulish_Bold',
    secondaryFontFamilySemiBold: 'Mulish_SemiBold',
    secondaryFontFamilyMedium: 'Mulish_Medium',
    secondaryFontFamilyRegular: 'Mulish_Regular',
    secondaryFontFamilyLight: 'Mulish_Light',
    secondaryFontFamilyExtraLight: 'Mulish_ExtraLight',
}